name: main
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: ndk
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: jdk
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 11
      - name: haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      - name: haxe libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel 4.11.0
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install flixel-addons 2.11.0
          haxelib git extension-videoview https://github.com/zatrit/extension-videoview.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib git extension-androidtools https://github.com/MaysLastPlay77/extension-androidtools.git
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: compile
        run: haxelib run lime build android
      - name: push
        uses: actions/upload-artifact@main
        with:
          name: build
          path: export/release/android/bin/app/build/outputs/apk/debug
